export { default as Home } from "./home/HomePage";
export { default as Error } from "./error/PageNotFound";
// export { default as ViewGameList } from "./game/GameListPage";
export { default as ViewGameAll } from "./game/GameAllPage";
export { default as ViewGameDetails } from "./game/GameDetailsPage";
export { default as ViewStoreAll } from "./store/StoreAllPage";
export { default as ViewStoreDetails } from "./store/StoreDetailsPage";
export { default as ViewCreatorAll } from "./creator/CreatorAllPage";
export { default as Login } from "./user/LoginPage";
export { default as Register } from "./user/RegisterPage";
export { default as Profile } from "./user/ProfilePage";